# Generated by Django 4.2 on 2023-10-16 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=100)),
                ('Gender', models.CharField(max_length=10)),
                ('PhoneNumber', models.CharField(max_length=15)),
                ('DOB', models.CharField(max_length=50)),
                ('SelectMembershipplan', models.CharField(max_length=50)),
                ('SelectTrainer', models.CharField(max_length=50)),
                ('Referance', models.CharField(max_length=50)),
                ('Address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MembershipPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(max_length=50)),
                ('price', models.IntegerField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=10)),
                ('salary', models.IntegerField(max_length=50)),
            ],
        ),
    ]
