# Generated by Django 4.2 on 2023-10-16 05:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_enrollment_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
