# Generated by Django 4.2 on 2023-11-04 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0008_enrollment_timestamp_gallery_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='phonenumber',
            field=models.CharField(max_length=13),
        ),
    ]
